### ISSUE TITLE
If u log out and log in, you lose your data [Android OnePlus One]

### ISSUE THREAD

**Issue by rgraciama** [jmtalarn/strikethru#10]
If u log out and log in (google account), you lose your data. 
But if you switch off the app (google account logged), and switch on the data returns :dancing_men: .

**Comment by jmtalarn** [comment]
Weird. Could you explain what is the difference between **"log in" and "log out"** and **"switch on" and "switch off"** ? Thank you.

**Comment by rgraciama** [comment]
I explain it by steps.

Pre step (logged in your app by google account).

1)  log out = settings>log out
2) then the data is lost. (It seems normal cause u are not logged)
3) after it, do log in with google account.
4) the data is not restored yet

**Comment by jmtalarn** [comment]
It will be hard to solve, not in the scope of this app while it is intended to work as a demo (for the moment). It requires a large development involving a change from Firebase  to another backend while we are using its Javascript SDK. 

You can check the following threads to get the thing
http://stackoverflow.com/questions/14670394/does-firebase-allow-an-app-to-start-in-offline-mode
https://groups.google.com/forum/#!topic/firebase-talk/5KrPMg-LhQk

Instead of implementing it as a feature we will add the requirement of Online connection on application startup.

**Comment by jmtalarn** [comment]
Closed this and reopened #5
